### ISSUE TITLE
Add a file/space in an existing file to identify the confidentiality of the work

### ISSUE THREAD

**Issue by adrianadepalma** [gthomab/PurvisTemplate#1]
Is the repo private because it's commercially sensitive and so should always be private? Who has access to the repo/work/output?
Is it private because it's going into a paper but could later be made public?
Can it be public at any time?

this could go in a separate file or maybe could be at the very start of the README file?

**Comment by gthomab** [comment]
Added to initial read me file - PurvisTemplate package will require a re-install for changes to be made.
